### ISSUE TITLE
Problem with Menu For Tablets

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/shop-isle#185]
1 - In chrome dev tools, menu collapses, but on browserstack menu does not collapse, it remains normal, on real devices it also remains normal like the desktop view. 

2 - Menus with sub items do not drop down on tablets. 

Two clients have reported the issue so far and they've confirmed (and I have checked with one of their websites) that they have the latest WordPress and theme so I don't think this might be a Jquery issue.

Tickets: 

http://themeisle.com/forums/topic/sub-menus-will-not-open-on-ipad/

This user also reports the drop down menu issue: http://themeisle.com/forums/topic/tablet-version-of-site-not-replicating-the-view-from-customiser/

@HardeepAsrani  @rodica-andronache

**Comment by rodica-andronache** [comment]
@UVLabs from what I've seen it seams maybe an issue of compatibility with MegaMenu plugin. On our site (without it) it seams to work ok. Could you please check again and let me know if the default menu within the theme it's working? and it's an issue with megamenu?

**Comment by UVLabs** [comment]
Ok I will.

**Comment by UVLabs** [comment]
@rodica-andronache this dropdown menu issue happens on the default menu, tested on latest version of theme and WordPress on a fresh install, no plugins activated.

I used browserstack for testing

**Comment by rodica-andronache** [comment]
@claudiuvertistudio can you please check this when you have time? I too tested on an ipad in browserstack and the dropdown menu doesn't seam to work

**Comment by geraldreisner** [comment]
When unsing Submenus in the Main Menu with Desktops, everything ist fine.
When viewing it on Tablets or Smartphones the Submenu does not open.
Even the Demo (http://themeisle.com/demo/?theme=ShopIsle) does not work on mobiles like i expect it. Try it with a real deice (not a simulation in the browser). Menu “New Coleection” on the top right. You can not click on “Checkout”, because the Menu does not open when.

You can, if you try it with a Desktop. But you can not if you try it with an Ipad, Windows Phone or Android device. It works in the simulation, but not with the real device. I love this Themes, pleas help!

Sorry for my poor english…
Gerald

**Comment by UVLabs** [comment]
Alot of people might be losing sales because of this bug without them even knowing @claudiuvertistudio
